
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author roan sampang
 */
public class RPS extends javax.swing.JFrame {

    /**
     * Creates new form RPS
     */
    public RPS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        txtp1 = new javax.swing.JTextField();
        txtp2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        p1health = new javax.swing.JLabel();
        p2health = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));
        getContentPane().add(txtp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 110, -1));
        getContentPane().add(txtp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 110, -1));

        jLabel1.setText("Player 2:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        jLabel2.setText("Player 1:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        p1health.setText("5");
        getContentPane().add(p1health, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 40, -1));

        p2health.setText("5");
        getContentPane().add(p2health, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 40, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int player1 = Integer.parseInt(txtp1.getText());
        int player2 = Integer.parseInt(txtp2.getText());
        int p1_hlth = Integer.parseInt(p1health.getText());
        int p2_hlth = Integer.parseInt(p2health.getText());
        
        if( player1 == 1 && player2 == 1 || player1 == 2 && player2 == 2 || player1 == 3 && player2 == 3 )
        {
            JOptionPane.showMessageDialog(rootPane, "draw", "status",JOptionPane.DEFAULT_OPTION);
        }
        else if(player1 == 1 && player2 == 2 || player1 == 2 && player2 == 3 || player1 == 3 && player2 == 1 )
      {
          p1_hlth = p1_hlth -1;
          p1health.setText(String.valueOf(p1_hlth));
           JOptionPane.showMessageDialog(rootPane, "player2 WIN", "status",JOptionPane.DEFAULT_OPTION);
        }
              else if(player1 == 2 && player2 == 1 || player1 == 3 && player2 == 2 || player1 == 1 && player2 == 3 )
      {
          p2_hlth = p2_hlth -1;
          p2health.setText(String.valueOf(p2_hlth));
           JOptionPane.showMessageDialog(rootPane, "player1 WIN", "status",JOptionPane.DEFAULT_OPTION);
           
        }
        if(p2_hlth == 0 || p1_hlth == 0){JOptionPane.showMessageDialog(rootPane, "game over!", "status",JOptionPane.DEFAULT_OPTION);}
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RPS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel p1health;
    private javax.swing.JLabel p2health;
    private javax.swing.JTextField txtp1;
    private javax.swing.JTextField txtp2;
    // End of variables declaration//GEN-END:variables
}
